title: Till Meineke # my name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # my text below (remove <br> elements if I don't need line breaks)
  Trainee Data Analyst
  <br><br>
  ğŸ‘¨ğŸ¼â€ğŸ’» I'm a Data Analyst with special interest in biological data and machine learning.
  <br><br>
  <a href="https://www.linkedin.com/in/tillmeineke">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
